package com.frontlineed.teambitwise.activities;

/**
 * Created by Robert on 4/12/2017.
 */
public enum ActivityType
{
    UNKNOWN,
    BITWISE_AND,
    ANIMALRACE,
    GOJOGGING,
    TEMPERATURECONVERT,
    GETALLACTIVITIES,
    TICTACTOE,
    READALPHABETFILE,
    READALPHABETFILEWITHNIO,
    READALPHABETFILETRYWITHRESOURCES,
    LAMBDAEXPRESSIONDEMO,
    GETORGANIZED,
    EXIT
}
